---
- name: Add authorized key
  hosts: all
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
    - name: Add user authorized key
      authorized_key:
        user: deploy
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"